"""Convert a CamTool camera JSON file into a Lua table literal.

The Lua tests have no JSON parser -- parsing is CSP's job in game -- so real
camera files are converted here to be used as fixtures.

Usage, from apps/lua/CamTool3POC:
    python tools/json_to_lua.py <input.json> <output.lua> [max_cameras]

max_cameras trims each of the two camera lists, so a versioned fixture keeps
the real shape and real values without carrying a whole 100 kB camera set.
"""
import json
import os
import sys

# Lua reserved words cannot be used as bare table keys.
RESERVED = set("""and break do else elseif end false for function if in local nil
not or repeat return then true until while""".split())


def is_plain_key(key):
    if not isinstance(key, str) or key in RESERVED:
        return False
    if not key or key[0].isdigit():
        return False
    return all(c.isalnum() or c == '_' for c in key)


def to_lua(value, indent=0):
    pad = '  ' * indent
    inner = '  ' * (indent + 1)

    if value is None:
        # JSON null. Lua nil would erase the key entirely, which would change
        # the shape of the data, so keep it visible as false.
        return 'false'
    if value is True:
        return 'true'
    if value is False:
        return 'false'
    if isinstance(value, (int, float)):
        if isinstance(value, float):
            if value != value:
                return '0/0'
            if value == float('inf'):
                return 'math.huge'
            if value == float('-inf'):
                return '-math.huge'
        return '%.17g' % value

    if isinstance(value, str):
        escaped = value.replace('\\', '\\\\').replace("'", "\\'")
        escaped = escaped.replace('\n', '\\n').replace('\r', '\\r')
        return "'%s'" % escaped

    if isinstance(value, list):
        if not value:
            return '{}'
        parts = ['%s%s,' % (inner, to_lua(v, indent + 1)) for v in value]
        return '{\n%s\n%s}' % ('\n'.join(parts), pad)

    if isinstance(value, dict):
        if not value:
            return '{}'
        parts = []
        # Sorted so regenerating a fixture gives a stable diff; Python dict
        # order and Lua table order are both unreliable anyway.
        for k in sorted(value.keys(), key=str):
            rendered = to_lua(value[k], indent + 1)
            if is_plain_key(k):
                parts.append('%s%s = %s,' % (inner, k, rendered))
            else:
                parts.append("%s['%s'] = %s," % (inner, k, rendered))
        return '{\n%s\n%s}' % ('\n'.join(parts), pad)

    raise TypeError('cannot render %r' % type(value))


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 1

    src, dst = sys.argv[1], sys.argv[2]
    max_cameras = int(sys.argv[3]) if len(sys.argv) > 3 else None

    with open(src, encoding='utf-8') as f:
        doc = json.load(f)

    if max_cameras is not None:
        for mode in ('time', 'pos'):
            if isinstance(doc.get(mode), list):
                doc[mode] = doc[mode][:max_cameras]

    header = (
        '-- GENERATED by tools/json_to_lua.py from %s\n'
        '-- A real CamTool 2 camera file, for testing the migration against\n'
        '-- data that users actually have. Do not edit by hand.\n'
        % os.path.basename(src)
    )

    outdir = os.path.dirname(dst)
    if outdir and not os.path.isdir(outdir):
        os.makedirs(outdir)

    with open(dst, 'w', encoding='utf-8', newline='\n') as f:
        f.write(header + 'return ' + to_lua(doc) + '\n')

    print('wrote %s (%d bytes)' % (dst, os.path.getsize(dst)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
