-- GENERATED by tools/gen_golden.py -- do not edit by hand.
-- Source of truth: CubicBezierInterpolation.SolveCubic
-- Each row is {name, a, b, c, d, result}. false means None was returned;
-- a string means the legacy RAISED that exception, which its callers
-- swallow into None.
return {
  {'a0_b0_returns_c', 0, 0, 0, 5, 5},
  {'a0_linear', 0, 0, 2, 4, -2},
  {'a0_quadratic_root_in_range', 0, 1, -1, 0.25, 0.5},
  {'a0_quadratic_negative_discriminant', 0, 1, 0, 1, 'TypeError'},
  {'d0_shortcut', 1, 0, 0, 0, 0},
  {'disc_positive', 1, 0, 0, -0.125, 0.5},
  {'disc_zero_root_in_range', 1, 0, -0.1875, -0.03125, 'NameError'},
  {'disc_zero_roots_out_of_range', 1, 0, -3, -2, false},
  {'disc_negative_three_real_roots', 1, -1.5, 0.5, -0.02, 0.04620828966294499},
  {'disc_negative_all_out_of_range', 1, 3, -4, -12, false},
}
