--[[
  Regenerate tests/fixtures/playback_golden.lua.

  The golden is a characterisation record: the camera the app drives, frame by
  frame, over a lap, exactly as the code stands today. It is not a statement
  that these numbers are right -- it is a statement that refactoring must not
  change them. Regenerate it only when a change to the camera's behaviour is
  intended, and say so in the commit message.

  Usage, from apps/lua/CamTool3:
      luajit tools/gen_playback_golden.lua
]]

package.path = './?.lua;' .. package.path

local lap = require('tests/lap')

local FRAMES = 600
-- Every row would be 600 lines of thirteen numbers. Sampling keeps the fixture
-- readable, and costs nothing: the app carries state from frame to frame (the
-- car history, the held aim, the shake window), so a divergence at any frame
-- is still there at the next sampled one.
local STEP = 8

local SCENARIOS = {
  {
    name = 'red_bull_ring',
    fixture = 'tests/fixtures/camera_file_lap',
    note = 'Red Bull Ring, whole file: eleven cameras and a real recorded '
        .. 'track path, so the lap crosses ten switches with the car where a '
        .. 'car really drove.',
  },
  {
    name = 'lancone_legacy_wrap',
    fixture = 'tests/fixtures/camera_file_lastcam',
    note = 'Le Lancone, 48 cameras. Its last camera keyframes 0.947 to 0.964 '
        .. 'without storing them wrapped, so the legacy wrap freezes it on its '
        .. 'first keyframe -- issue #23, recorded as it stands.',
  },
  {
    name = 'lancone_fixed_wrap',
    fixture = 'tests/fixtures/camera_file_lastcam',
    checkboxes = { 'legacy last-camera wrap (#23)' },
    note = 'The same lap with the #23 fix on. These two scenarios must differ '
        .. 'over the last camera and nowhere else; that is what makes the fix '
        .. 'a fix rather than a change of behaviour.',
  },
  {
    name = 'silverstone_splines',
    fixture = 'tests/fixtures/camera_file_splines',
    note = 'Silverstone seb, cameras driven by recorded paths. No track path '
        .. 'in the file, so the car runs the stand-in circle.',
  },
}

local out = {}
local function emit(line) out[#out + 1] = line end

emit('-- GENERATED by tools/gen_playback_golden.lua -- do not edit by hand.')
emit('--')
emit('-- What the app asks of the camera, frame by frame, over a lap. See the')
emit('-- generator for what this is for and when to regenerate it.')
emit('return {')
emit(string.format('  frames = %d,', FRAMES))
emit(string.format('  step = %d,', STEP))
emit('  fields = {')
for _, field in ipairs(lap.FIELDS) do
  emit(string.format('    %q,', field))
end
emit('  },')
emit('  scenarios = {')

for _, scenario in ipairs(SCENARIOS) do
  io.write('running ', scenario.name, ' ... ')
  io.flush()

  local result = lap.run({
    cameraFile = require(scenario.fixture),
    frames = FRAMES,
    checkboxes = scenario.checkboxes,
  })
  result.handle.restoreIo()

  emit('    {')
  emit(string.format('      name = %q,', scenario.name))
  emit(string.format('      fixture = %q,', scenario.fixture))
  if scenario.checkboxes ~= nil then
    emit('      checkboxes = {')
    for _, label in ipairs(scenario.checkboxes) do
      emit(string.format('        %q,', label))
    end
    emit('      },')
  end
  emit(string.format('      note = %q,', scenario.note))
  emit('      rows = {')

  local kept = 0
  for i = STEP, FRAMES, STEP do
    local row = result.frames[i]
    local parts = { string.format('%d', i) }
    for _, field in ipairs(lap.FIELDS) do
      parts[#parts + 1] = string.format('%.17g', row[field])
    end
    emit('        { ' .. table.concat(parts, ', ') .. ' },')
    kept = kept + 1
  end

  emit('      },')
  emit('    },')
  print(string.format('%d frames, %d rows kept', FRAMES, kept))
end

emit('  },')
emit('}')

local path = 'tests/fixtures/playback_golden.lua'
local file = assert(io.open(path, 'wb'))
file:write(table.concat(out, '\n'), '\n')
file:close()
print('wrote ' .. path)
