"""Generate golden-master fixtures for the Lua interpolation port.

Runs the REAL legacy interpolator (classes/CubicBezierInterpolation.py, which
imports nothing but math) and records what it returns, so the Lua port is
checked against the Python that actually produced users' videos rather than
against anyone's reading of it.

Output is a Lua file, not JSON: the test runner has no JSON parser and the
whole toolchain is meant to stay at zero dependencies. Floats are written with
%.17g, which round-trips a double exactly.

Usage, from apps/lua/CamTool3:
    python tools/gen_golden.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
AC_ROOT = os.path.abspath(os.path.join(APP, '..', '..', '..'))
LEGACY = os.path.join(AC_ROOT, 'apps', 'python', 'CamTool_2', 'classes')

sys.path.insert(0, LEGACY)
import CubicBezierInterpolation as legacy  # noqa: E402

OUT = os.path.join(APP, 'tests', 'fixtures', 'interpolation_golden.lua')
OUT_CUBIC = os.path.join(APP, 'tests', 'fixtures', 'cubic_golden.lua')

# Each case is (name, x, y). x is keyframe positions, y the values at them.
CASES = [
    ('empty', [], []),
    ('single', [0.5], [42.0]),
    ('two_rising', [0.0, 1.0], [0.0, 10.0]),
    ('two_falling', [0.2, 0.8], [5.0, -5.0]),
    ('four_uneven', [0.0, 0.25, 0.5, 1.0], [0.0, 10.0, -5.0, 3.0]),
    ('flat', [0.0, 0.3, 0.7, 1.0], [2.5, 2.5, 2.5, 2.5]),
    # tx == 0 branch in interpolate_sin: two keyframes at the same position.
    ('duplicate_x', [0.0, 0.4, 0.4, 1.0], [0.0, 1.0, 9.0, 3.0]),
    ('negative_values', [-1.0, 0.0, 1.0], [-100.0, 0.0, 100.0]),
    # Taken from data/ks_red_bull_ring_layout_gp-init.json: stored FOV values
    # and a world coordinate, so the fixture covers the magnitudes that show up
    # in real camera files.
    ('real_fov_stored', [0.036643, 0.171270, 0.5, 0.9],
     [0.04218635740990599, 0.058823529411764705, 0.0421863574099, 0.06]),
    ('real_world_coord', [0.0, 0.2, 0.55, 1.0],
     [-173.3106689453125, 448.1579284667969, 33.39756774902344, -364.91473388671875]),
]


# Raw coefficients for SolveCubic, chosen to walk every branch of the solver:
# the quadratic fallback, the d == 0 shortcut, and each sign of the
# discriminant. The solver is where the numerics actually live, so it gets
# fixtures of its own rather than only being exercised through interpolate.
CUBIC_CASES = [
    ('a0_b0_returns_c', 0.0, 0.0, 0.0, 5.0),
    ('a0_linear', 0.0, 0.0, 2.0, 4.0),
    ('a0_quadratic_root_in_range', 0.0, 1.0, -1.0, 0.25),
    ('a0_quadratic_negative_discriminant', 0.0, 1.0, 0.0, 1.0),
    ('d0_shortcut', 1.0, 0.0, 0.0, 0.0),
    ('disc_positive', 1.0, 0.0, 0.0, -0.125),
    # disc == 0 with the single root inside [0, 1]: trips `return result`,
    # which is a NameError in the legacy.
    ('disc_zero_root_in_range', 1.0, 0.0, -0.1875, -0.03125),
    # disc == 0 with both roots outside [0, 1]: falls through cleanly.
    ('disc_zero_roots_out_of_range', 1.0, 0.0, -3.0, -2.0),
    ('disc_negative_three_real_roots', 1.0, -1.5, 0.5, -0.02),
    ('disc_negative_all_out_of_range', 1.0, 3.0, -4.0, -12.0),
]


def call(fn, *args):
    """Return the value, or the exception's class name when it raises.

    The legacy leans on exceptions: callers wrap these in try/except and turn a
    raise into None. Recording which inputs raise is therefore part of the
    behaviour being pinned, not an accident of the harness.
    """
    try:
        return fn(*args)
    except Exception as exc:
        return type(exc).__name__


def lua_value(v):
    if isinstance(v, str):
        return "'%s'" % v
    if isinstance(v, complex):
        return "'complex'"
    return lua_number(v)


def sample_times(x):
    """Knots themselves, midpoints, and points outside the range."""
    times = [-0.5, -0.001, 0.0, 0.5, 1.0, 1.5]
    for v in x:
        times.extend([v - 1e-6, v, v + 1e-6])
    for i in range(len(x) - 1):
        times.append((x[i] + x[i + 1]) / 2.0)
    return sorted(set(times))


def lua_number(v):
    if v is None:
        return 'false'  # nil would punch a hole in the array
    if v != v:
        return '0/0'
    if v == float('inf'):
        return 'math.huge'
    if v == float('-inf'):
        return '-math.huge'
    return '%.17g' % v


def main():
    interp = legacy.CubicBezierInterpolation()
    lines = [
        '-- GENERATED by tools/gen_golden.py -- do not edit by hand.',
        '-- Source of truth: apps/python/CamTool_2/classes/CubicBezierInterpolation.py',
        '-- Each row is {time, interpolate, interpolate_sin, interpolate_spline,',
        '-- interpolate_spline_cyclic}. false means the legacy returned None.',
        'return {',
    ]
    total = 0
    for name, x, y in CASES:
        lines.append('  {')
        lines.append('    name = %r,' % name)
        lines.append('    x = {%s},' % ', '.join(lua_number(v) for v in x))
        lines.append('    y = {%s},' % ', '.join(lua_number(v) for v in y))
        lines.append('    rows = {')
        for t in sample_times(x):
            row = [
                t,
                interp.interpolate(t, list(x), list(y)),
                interp.interpolate_sin(t, list(x), list(y)),
                interp.interpolate_spline(t, list(x), list(y), False),
                interp.interpolate_spline(t, list(x), list(y), True),
            ]
            lines.append('      {%s},' % ', '.join(lua_number(v) for v in row))
            total += 1
        lines.append('    },')
        lines.append('  },')
    lines.append('}')

    cubic_lines = [
        '-- GENERATED by tools/gen_golden.py -- do not edit by hand.',
        '-- Source of truth: CubicBezierInterpolation.SolveCubic',
        '-- Each row is {name, a, b, c, d, result}. false means None was returned;',
        '-- a string means the legacy RAISED that exception, which its callers',
        '-- swallow into None.',
        'return {',
    ]
    for name, a, b, c, d in CUBIC_CASES:
        got = call(interp.SolveCubic, a, b, c, d)
        cubic_lines.append('  {%r, %s, %s, %s, %s, %s},'
                           % (name, lua_number(a), lua_number(b),
                              lua_number(c), lua_number(d), lua_value(got)))
    cubic_lines.append('}')

    outdir = os.path.dirname(OUT)
    if not os.path.isdir(outdir):
        os.makedirs(outdir)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print('wrote %s' % OUT)
    print('%d cases, %d sampled points' % (len(CASES), total))

    with open(OUT_CUBIC, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(cubic_lines) + '\n')
    print('wrote %s' % OUT_CUBIC)
    print('%d cubic solver cases' % len(CUBIC_CASES))


if __name__ == '__main__':
    main()
