"""Convert a CamTool 2 trace (JSON Lines) into a Lua table literal.

CamTool 2 records what it was told and what it asked of the camera, one JSON
object per frame -- see apps/python/CamTool_2/classes/trace.py. The Lua tests
have no JSON parser, parsing being CSP's job in game, so a trace is converted
here the same way real camera files already are.

Usage, from apps/lua/CamTool3:
    python tools/trace_to_lua.py <trace.jsonl> <output.lua> [max_frames]

max_frames trims the trace, so a versioned fixture keeps real values without
carrying two minutes of frames. A recording is not reproducible, so keep the
.jsonl beside the .lua: it is the original, and the .lua is a reading of it.
"""
import json
import os
import sys


# Lua reserved words cannot be used as bare table keys. No field is called any
# of these today, but a trace is written by another program and read as code.
RESERVED = set("""and break do else elseif end false for function if in local nil
not or repeat return then true until while""".split())


def key_of(name):
    plain = bool(name) and name not in RESERVED and not name[0].isdigit()
    if plain and all(c.isalnum() or c == '_' for c in name):
        return name
    escaped = name.replace('\\', '\\\\').replace("'", "\\'")
    return "['%s']" % escaped


def to_lua_number(value):
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, float):
        if value != value:
            return '0/0'
        if value == float('inf'):
            return 'math.huge'
        if value == float('-inf'):
            return '-math.huge'
    return '%.17g' % value


def to_lua_value(value):
    if value is None:
        return 'nil'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, (int, float)):
        return to_lua_number(value)
    if isinstance(value, str):
        escaped = value.replace('\\', '\\\\').replace("'", "\\'")
        return "'%s'" % escaped
    if isinstance(value, list):
        return '{ %s }' % ', '.join(to_lua_value(v) for v in value)
    raise TypeError('cannot render %r in a trace row' % type(value))


def read_trace(path):
    """Return (header, rows). Raises on anything that is not a trace."""
    header = None
    rows = []

    with open(path, encoding='utf-8') as handle:
        for number, line in enumerate(handle, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except ValueError as error:
                raise ValueError('line %d is not JSON: %s' % (number, error))

            if record.get('type') == 'header':
                if header is not None:
                    raise ValueError('line %d: a second header' % number)
                header = record
            else:
                rows.append(record)

    if header is None:
        raise ValueError('%s has no header line' % path)
    if not rows:
        raise ValueError('%s has a header and no frames' % path)

    return header, rows


# Written first on every row, so a glance down the file reads as a timeline.
LEADING_KEYS = ['f', 'x', 'dt']


def render_row(row):
    keys = list(LEADING_KEYS)
    for key in sorted(row.keys()):
        if key not in keys:
            keys.append(key)

    parts = []
    for key in keys:
        if key in row:
            parts.append('%s = %s' % (key_of(key), to_lua_value(row[key])))
    return '{ %s }' % ', '.join(parts)


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 1

    src, dst = sys.argv[1], sys.argv[2]
    max_frames = int(sys.argv[3]) if len(sys.argv) > 3 else None

    header, rows = read_trace(src)
    if max_frames is not None:
        rows = rows[:max_frames]

    out = []
    out.append('-- GENERATED by tools/trace_to_lua.py from %s'
               % os.path.basename(src))
    out.append('-- A CamTool 2 trace: what it was told and what it asked of the')
    out.append('-- camera, frame by frame. Do not edit by hand.')
    out.append('return {')
    out.append('  header = {')
    for key in sorted(header.keys()):
        out.append('    %s = %s,' % (key_of(key), to_lua_value(header[key])))
    out.append('  },')
    out.append('  frames = {')
    for row in rows:
        out.append('    %s,' % render_row(row))
    out.append('  },')
    out.append('}')

    with open(dst, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write('\n'.join(out))
        handle.write('\n')

    print('wrote %s (%d frames)' % (dst, len(rows)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
